### ISSUE TITLE
Diff in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/orb#52] opened 2020-02-03 12:14 UTC
See https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/645232349
```
########> Diff in /home/gap/inst/gap-master/pkg/orb-4.8.3/tst/bugfix.tst:7
# Input is:
Enumerate(o);
# Expected output:
<closed orbit, 2 points>
# But found:
<closed orbit, 3 points>
########
```

**Comment by alex-konovalov** [comment] 2020-02-03 12:15
Note that this still works in stable-4.11, so adjusting the test to new output (if it's correct) will break the tests there.

**Comment by fingolfin** [comment] 2020-02-03 21:15
The output is wrong, this is caused by an issue in GAP master, which I'll have to fix there.

**Comment by fingolfin** [comment] 2020-02-03 21:39
Fixed by https://github.com/gap-system/gap/pull/3882

**Closed** 2020-02-05 10:23 UTC
